2025-10-18 13:14:20,224 - ERROR - Необработанное исключение: AttributeError: 'MainWindow' object has no attribute 'r_update'
2025-10-18 13:14:20,224 - ERROR - Трассировка стека:
Traceback (most recent call last):
  File "c:\Users\Alex_SSHOR13\Competitions_TT\main.py", line 1219, in <module>
    my_win = MainWindow()
             ^^^^^^^^^^^^
  File "c:\Users\Alex_SSHOR13\Competitions_TT\main.py", line 272, in __init__
    self._connectActions()
  File "c:\Users\Alex_SSHOR13\Competitions_TT\main.py", line 626, in _connectActions
    self.r_update_Action.triggered.connect(self.r_update)
                                           ^^^^^^^^^^^^^
AttributeError: 'MainWindow' object has no attribute 'r_update'
