2025-10-18 11:30:45,243 - ERROR - Необработанное исключение: ValueError: r_date is not null but has no default
2025-10-18 11:30:45,244 - ERROR - Трассировка стека:
Traceback (most recent call last):
  File "c:\Users\Alex_SSHOR13\Competitions_TT\main.py", line 19840, in proba
    migrate(migrator.add_column('titles', 'r_date', CharField()))
  File "C:\Users\Alex_SSHOR13\Competitions_TT\venv\Lib\site-packages\playhouse\migrate.py", line 947, in migrate
    operation.run()
  File "C:\Users\Alex_SSHOR13\Competitions_TT\venv\Lib\site-packages\playhouse\migrate.py", line 162, in run
    self._handle_result(method(*self.args, **kwargs))
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Alex_SSHOR13\Competitions_TT\venv\Lib\site-packages\playhouse\migrate.py", line 170, in inner
    return fn(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Alex_SSHOR13\Competitions_TT\venv\Lib\site-packages\playhouse\migrate.py", line 320, in add_column
    raise ValueError('%s is not null but has no default' % column_name)
ValueError: r_date is not null but has no default
